-- Users Table
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL, -- In a real app, store hashes!
    full_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100)
);

-- Accounts Table
CREATE TABLE accounts (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(user_id),
    account_number VARCHAR2(20) UNIQUE NOT NULL,
    balance NUMBER(15, 2) DEFAULT 0,
    savings_balance NUMBER(15, 2) DEFAULT 0,
    savings_goal NUMBER(15, 2) DEFAULT 1000,
    spending_limit NUMBER(15, 2) DEFAULT 5000,
    card_number VARCHAR2(16),
    card_expiry VARCHAR2(5), -- MM/YY
    card_cvv VARCHAR2(3)
);

-- Transactions Table
CREATE TABLE transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_account_id NUMBER REFERENCES accounts(account_id),
    to_account_id NUMBER REFERENCES accounts(account_id), -- Can be null for external payments
    amount NUMBER(15, 2) NOT NULL,
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    description VARCHAR2(200),
    type VARCHAR2(20), -- 'TRANSFER', 'PAYMENT', 'DEPOSIT'
    status VARCHAR2(20) DEFAULT 'COMPLETED' -- 'PENDING', 'COMPLETED'
);
-- Insert Vorxiu User
INSERT INTO users (username, password, full_name, email) 
VALUES ('vorxiu', 'vorxiu123', 'Vorxiu User', 'vorxiu@example.com');

INSERT INTO accounts (user_id, account_number, balance, savings_balance, savings_goal, spending_limit, card_number, card_expiry, card_cvv)
VALUES (2, '998877', 25000.00, 500.00, 5000.00, 10000.00, '5000123456789010', '10/30', '456');

-- History for Vorxiu
INSERT INTO transactions (from_account_id, amount, description, type, status)
VALUES (2, 50.00, 'Netflix Subscription', 'PAYMENT', 'COMPLETED');

INSERT INTO transactions (from_account_id, amount, description, type, status)
VALUES (2, 1200.00, 'Rent Payment', 'PAYMENT', 'COMPLETED');

INSERT INTO transactions (to_account_id, amount, description, type, status)
VALUES (2, 5000.00, 'Freelance Work', 'DEPOSIT', 'COMPLETED');

INSERT INTO transactions (from_account_id, amount, description, type, status)
VALUES (2, 45.99, 'Amazon Purchase', 'PAYMENT', 'PENDING');

INSERT INTO transactions (from_account_id, amount, description, type, status)
VALUES (2, 15.00, 'Spotify', 'PAYMENT', 'COMPLETED');

COMMIT;

-- Add Vorxiu User
INSERT INTO users (username, password, full_name, email) 
VALUES ('vorxiu', 'vorxiu123', 'Vorxiu User', 'vorxiu@example.com');

-- Add Account for Vorxiu
INSERT INTO accounts (user_id, account_number, balance, savings_balance, savings_goal, spending_limit, card_number, card_expiry, card_cvv)
SELECT user_id, '987654321', 25000.00, 500.00, 5000.00, 1000.00, '5000123456789012', '10/29', '456'
FROM users WHERE username = 'vorxiu';

-- Add Transactions for Vorxiu
INSERT INTO transactions (from_account_id, amount, description, type, status)
SELECT account_id, 50.00, 'Coffee Shop', 'PAYMENT', 'COMPLETED'
FROM accounts a JOIN users u ON a.user_id = u.user_id WHERE u.username = 'vorxiu';

INSERT INTO transactions (from_account_id, amount, description, type, status)
SELECT account_id, 1200.00, 'Rent Payment', 'PAYMENT', 'COMPLETED'
FROM accounts a JOIN users u ON a.user_id = u.user_id WHERE u.username = 'vorxiu';

INSERT INTO transactions (to_account_id, amount, description, type, status)
SELECT account_id, 5000.00, 'Freelance Project', 'DEPOSIT', 'COMPLETED'
FROM accounts a JOIN users u ON a.user_id = u.user_id WHERE u.username = 'vorxiu';

INSERT INTO transactions (from_account_id, amount, description, type, status)
SELECT account_id, 200.00, 'Utilities', 'PAYMENT', 'PENDING'
FROM accounts a JOIN users u ON a.user_id = u.user_id WHERE u.username = 'vorxiu';

COMMIT;
